In [1]:
from sentence_transformers import SentenceTransformer, util
import numpy as np

In [2]:
from barracuda_networks.data_retriever import *

reviews, target_review, filenames = get_reviews_as_list_of_texts(return_file_names=True)
# print(target_review)bin

FOUND TARGET LINE OF: This was the first Ewan McGregor movie I ever saw outside of Star Wars. Since then I have become a very big Ewan McGregor fan but I still can't bring myself to forgive this movie's existence.<br /><br />My sister has always been a huge Jane Austen fan and because of that, I have been subjected to various of the classics, Emma being one of them. I've always considered them irritating, stupid and boring. However, after watching this terrible rendition, I was forced to admit that the original Emma was delightful and charming. Ewan McGregor scarcely serves a purpose in this film after they hacked and mutilated the part of Frank Churchill. Gweneth Paltrow is ridiculous in an already ridiculous character and the rest of the film is unremarkable and stupid.<br /><br />My recommendation to anybody who is remotely interested in English period drama... go see the originals. If you're a Ewan McGregor fan... believe me, by skipping this film, you haven't missed anything but f

In [3]:
filenames[0]

'barracuda_networks/aclImdb/train/unsup/18512_0.txt'

In [4]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


In [5]:
df = pd.DataFrame(data={"reviews": reviews})

In [6]:
df.shape

(50000, 1)

In [19]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(reviews)

In [20]:
target = vectorizer.transform([target_review])

In [21]:
tmp = cosine_similarity(target, X)

In [22]:
tmp[0]

array([0.09404602, 0.1188567 , 0.06981961, ..., 0.10696507, 0.08451879,
       0.05683232])

In [23]:
indices = np.argpartition(tmp[0], -10)[-10:]

In [24]:
indices

array([10982, 36481, 44579, 24887,   701,  5143, 12128, 46254, 12390,
       14903])

In [26]:
tmp[0]

array([0.09404602, 0.1188567 , 0.06981961, ..., 0.10696507, 0.08451879,
       0.05683232])

In [12]:
for i in indices:
    print(filenames[i])
    print(reviews[i])
    print("\n")

barracuda_networks/aclImdb/train/unsup/18899_0.txt
i think the main problem with the movie isn't the movie, it's that people are going in expecting a thriller instead of a drama. yes the major plot points could be covered in 5 minutes.. but that's not the point of drama. your average thriller is about things that happen and happen to have people in them. this movie is about the people and how they feel and cope when something momentous happens. if you appreciate that you'll appreciate the movie better, or not watch it cos it's not something that appeals to you.. and that's fair enough.<br /><br />As far as the film goes, Michelle Williams carries it well. The accent's fine and the various states she goes through as she tries to deal with what has happened never feel you leaving disconnected or not understanding how she got there.<br /><br />McGregor is his usual charming self, tho his is not really a major part (likewise MacFadyen), this is a movie about the mother and so these two don